# Generated by Django 5.1.4 on 2024-12-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Length", models.FloatField()),
                ("Width", models.FloatField()),
                ("Height", models.FloatField()),
                ("Number_of_pieces_per_box", models.IntegerField()),
                ("Total_quantity", models.IntegerField()),
                ("Box_weight", models.FloatField()),
                ("Cost_per_piece", models.FloatField()),
                ("Density", models.FloatField()),
                ("Logistics_naked", models.FloatField()),
                ("Logistics", models.FloatField()),
                ("Packaging_Regular", models.FloatField()),
                ("Unloading_at_MSK", models.FloatField()),
                ("Total_cost_per_unit", models.FloatField()),
                ("Total_logistics_cost", models.FloatField()),
                ("Insurance", models.FloatField()),
                ("Packaging", models.FloatField()),
                ("Unloading", models.FloatField()),
                ("Total_cost_of_the_lot", models.FloatField()),
                ("Date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypeOfOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("cost", models.FloatField()),
            ],
        ),
    ]
